Part one of version 2.1
Error: diff is to huge to write a commit message for!

Part 1:
* I'm rewriting the markup. I've done some of the markup (head, header,
navigation)
* I'm rewriting the CSS as well. All the code CSS is commented out. Some
of it comes back, some is being killed
* The width is now 1140px. I've implemented some layout code from
Twitter Bootstrap
* The demo markup on the about page is being done better thanks to the
markup from Twitter Bootstrap demo
* Modernizr 2.5.3
* Use Normalize.css instead of a reset.css
* Use Open Sans and Merriweather from Google Fonts
* And more

Part 2:
* Rewrite the rest of the markup
* Rewrite the rest of the CSS
* Decide whether to have a semi transport or a white background on the
main content
* Browser testing
* Responsive testing
* Print styles
* And much more